export const statesAbbreviation = [
  {id: '1', title: 'Сделать тестовое'},
  {id: '2', title: 'Сдать тестовое'},
  {id: '3', title: 'Начать зарабатывать'},
  {id: '4', title: 'AR'},
  {id: '5', title: 'CA'},
  {id: '6', title: 'CO'},
  {id: '7', title: 'CT'},
  {id: '8', title: 'DE'},
  {id: '9', title: 'DC'},
  {id: '10', title: 'FL'},
  {id: '11', title: 'GA'},
  {id: '12', title: 'HI'},
  {id: '13', title: 'ID'},
  {id: '14', title: 'IL'},
  {id: '15', title: 'IN'},
  {id: '16', title: 'IA'},
  {id: '17', title: 'KS'},
  {id: '18', title: 'KY'},
  {id: '19', title: 'LA'},
  {id: '20', title: 'ME'},
  {id: '21', title: 'MD'},
]
